### ISSUE TITLE
Getting this issue when deploying on netlify

### ISSUE THREAD

**Issue by kamranalam27** [CodeVinayak/Portfolio-v2#1]
Getting this issue when build this app with(npm run build). Although build has successfully created  but  when i opened the index file it shows a blank page containing these errors.
 
![p1](https://github.com/CodeVinayak/Portfolio-v2/assets/55096395/5c3b2360-436d-475f-89ec-9b1753d591d2)
![build img](https://github.com/CodeVinayak/Portfolio-v2/assets/55096395/366e3d37-2787-4ead-a8bc-7aa6f4e09f50)

**Comment by CodeVinayak** [comment]
To run this project:
- yarn install
- yarn run start

**Comment by kamranalam27** [comment]
Yes i know. but when i try to make a build for deployment then these error accurs.

**Comment by CodeVinayak** [comment]
deploy it on vercel with 
![image](https://github.com/CodeVinayak/Portfolio-v2/assets/86673265/a58b06b7-d3ed-46b6-a47c-604eb9ad7488)

**Comment by kamranalam27** [comment]
Where do I need to make changes? Please be precise. Additionally, I'm attempting to deploy on Netlify, but when I encountered an issue, I tried to build it locally and this happened.
![image](https://github.com/CodeVinayak/Portfolio-v2/assets/55096395/a1794de9-ce58-477f-881e-a3f73a2e85c4)
